apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin
    app.kubernetes.io/name: admin
    app.kubernetes.io/component: admin-panel
    app.kubernetes.io/part-of: shopnow
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: admin
    app.kubernetes.io/name: admin
